services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Iepg\Bundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'
 
  Iepg\Bundle\Service\WithParameterService: 
    - '%iepg_test.my_var_string%'
    - '%iepg_test.my_var_string_option%'